name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: "${{ matrix.os }} - ${{ matrix.node }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            tag: linux
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            tag: experimental
            node-version: 21.x
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node }}
      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1
      - name: Perform some tests
        run: | 
          echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
          sleep 10
      - name: Upload test results
        run: echo Uploading test results

